name = input("사용자 이름을 입력하세요 : ")
call = float(input("통화량(초)를 입력하세요 : "))
data = float(input("데이터 사용량(MB)를 입력하세요 : "))
calculate = 12100 + (call * 1.98) + (data * 55)
print(name, "님의 이번달 요금 :", calculate)
